"""Enumeration mappings for the HDG Bavaria Boiler integration.

This module defines mappings for HDG API enumeration values to human-readable text
(German and English). These mappings are crucial for interpreting and displaying
the state of sensor entities that represent enumerated values from the boiler,
such as operating modes, status codes, or configuration options.
"""

from __future__ import annotations


from typing import Final, TypedDict

from .models import EnumOption


class StringEnumOption(TypedDict):
    """Represent a single option within a string-keyed enumeration, providing translations.

    Used in `enums.py` for `HDG_STRING_ENUM_MAPPINGS`.
    """

    de: str
    en: str


HDG_ENUM_MAPPINGS: Final[dict[str, dict[int, EnumOption]]] = {
    "SPRACHE": {
        0: {"de": "Deutsch", "en": "Deutsch"},
        1: {"de": "Englisch", "en": "English"},
        2: {"de": "Dänisch", "en": "Danish"},
        3: {"de": "Französisch", "en": "French"},
        4: {"de": "Spanisch", "en": "Spanish"},
        5: {"de": "Italienisch", "en": "Italian"},
        6: {"de": "Niederländisch", "en": "Dutch"},
        7: {"de": "Norwegisch", "en": "Norwegian"},
        8: {"de": "Schwedisch", "en": "Swedish"},
        9: {"de": "Polnisch", "en": "Polish"},
        10: {"de": "Slowenisch", "en": "Slovenian"},
        11: {"de": "Tschechisch", "en": "Czech"},
        12: {"de": "Ungarisch", "en": "Hungarian"},
        13: {"de": "Russisch", "en": "Russian"},
        14: {"de": "Finnisch", "en": "Finnish"},
        15: {"de": "Lettisch", "en": "Latvian"},
        16: {"de": "Litauisch", "en": "Lithuanian"},
        17: {"de": "Estnisch", "en": "Estonian"},
        18: {"de": "Rumänisch", "en": "Romanian"},
        19: {"de": "Bulgarisch", "en": "Bulgarian"},
        20: {"de": "Kroatisch", "en": "Croatian"},
        21: {"de": "Serbisch", "en": "Serbian"},
        22: {"de": "Griechisch", "en": "Greek"},
        23: {"de": "Portugiesisch", "en": "Portuguese"},
    },
    "KESSELSTATUS": {
        0: {"de": "Störung", "en": "Fault"},
        1: {"de": "Bereit", "en": "Ready"},
        2: {"de": "Reinigung", "en": "Cleaning"},
        3: {"de": "Vorbelüften", "en": "Pre-ventilation"},
        4: {"de": "Füllen", "en": "Filling"},
        5: {"de": "Anzünden", "en": "Ignition"},
        6: {"de": "Anzünden kühlen", "en": "Cooling ignition"},
        7: {"de": "Anheizen", "en": "Heating-up"},
        8: {"de": "Automatik", "en": "Automatic"},
        9: {"de": "Ausbrennen", "en": "Burn out"},
        10: {"de": "Gluterhaltung", "en": "Keep embers glow"},
        11: {"de": "Lambdatest", "en": "Lambda test"},
        12: {"de": "Schutzprogramm", "en": "Protection program"},
        13: {"de": "Ausgeschaltet", "en": "Turned off"},
        14: {"de": "Zündung bereit", "en": "Ignition ready"},
        15: {"de": "Unbekannt 15", "en": "Unknown 15"},
        16: {"de": "Ausbrennen (SHK)", "en": "Burn out (SHK)"},
        17: {"de": "Abgastemp.–Stopp", "en": "Fluegas temp.stop"},
        18: {"de": "Restwärmenutzung", "en": "Resid.heat utilis."},
    },
    "AUSBRANDGRUND": {
        0: {"de": " ", "en": " "},
        1: {"de": "Rostkippung", "en": "Tip grate"},
        2: {"de": "Keine Anforderung", "en": "No demand"},
        3: {"de": "Abschaltung", "en": "Switch-off"},
    },
    "PUFFER_ZUSTAND": {
        0: {"de": "Aus", "en": "Off"},
        1: {"de": "Absenken", "en": "Lowering"},
        2: {"de": "Normal", "en": "Normal"},
        3: {"de": "Zwangsladung", "en": "Forced Charge"},
    },
    "AUS/AUF/ZU/STOERUNG": {
        0: {"de": "Aus", "en": "Off"},
        1: {"de": "Auf", "en": "Open"},
        2: {"de": "Zu", "en": "Closed"},
        3: {"de": "Störung", "en": "Fault"},
    },
    "OFF/ON/STOERUNG": {
        0: {"de": "Aus", "en": "Off"},
        1: {"de": "Ein", "en": "On"},
        2: {"de": "Störung", "en": "Fault"},
    },
    "HEIZKREIS_CURRENT": {
        0: {"de": "Abgesenkt", "en": "Reduced"},
        1: {"de": "Aus", "en": "Off"},
        2: {"de": "Standard", "en": "Standard"},
        3: {"de": "Tagbetrieb", "en": "Day mode"},
        4: {"de": "Nachtbetrieb", "en": "Night mode"},
        5: {"de": "Partybetrieb", "en": "Party mode"},
        6: {"de": "Urlaubsbetrieb", "en": "Holiday mode"},
        7: {"de": "Sommerbetrieb", "en": "Summer mode"},
    },
    "KESSEL_HBA": {
        0: {"de": "Ausgeschaltet", "en": "Turned off"},
        1: {"de": "Abschaltvorgang", "en": "Power down"},
        2: {"de": "Eingeschaltet", "en": "Turned on"},
        3: {"de": "Festwert", "en": "Fixed value"},
        4: {"de": "Schornsteinfeger", "en": "Chimney sweep"},
        5: {"de": "Aktoren Anlage", "en": "Actuator system"},
        6: {"de": "Aktoren Zuführung", "en": "Actuator feed"},
        7: {"de": "Autobinding", "en": "Autobinding"},
        8: {"de": "Unbekannt", "en": "Unknown"},
    },
    "HK_BETRIEBSPHASE": {
        0: {"de": "Störabschaltung", "en": "Fault shutdown"},
        1: {"de": "Brenner gesperrt", "en": "Burner disabled"},
        2: {"de": "WE einschalten", "en": "Turn on WE"},
        3: {"de": "Selbsttest", "en": "Self test"},
        4: {"de": "WE ausschalten", "en": "Turn off WE"},
        5: {"de": "Standby", "en": "Standby"},
        6: {"de": "Brenner aus", "en": "Burner off"},
        7: {"de": "Vorspülen", "en": "Flushing"},
        8: {"de": "Zündphase", "en": "Ignition phase"},
        9: {"de": "Flammenstabilisierung", "en": "Flame stabilisation"},
        10: {"de": "Modulationsbetrieb", "en": "Modulation phase"},
        11: {"de": "Modulation Fixleistung", "en": "Fix output modulation"},
        12: {"de": "Modulation Entaschung", "en": "De-ashing modulation"},
        13: {"de": "Ausbrand", "en": "Burn-out"},
        14: {"de": " ", "en": " "},
    },
    "NACHLEGEZEITPUNKT_BENACHRICHTIGUNG": {
        0: {"de": "Niemals", "en": "Never"},
        1: {"de": "bei Änderung um 30 min", "en": "if changed by 30 min"},
        2: {"de": "bei Änderung um 1 h", "en": "if changed by 1 h"},
        3: {"de": "bei Änderung um > 2 h", "en": "if changed by > 2 h"},
    },
    "HK_SYSTEM": {
        0: {"de": "Keines", "en": "None"},
        1: {"de": "Heizkörper", "en": "Radiators"},
        2: {"de": "Fußboden", "en": "Underfloor heat"},
        3: {"de": "Konstant", "en": "Constant"},
        4: {"de": "Ungeregelt", "en": "Uncontrolled"},
    },
    "BAUART": {
        0: {"de": "SAL", "en": "SAL"},
        1: {"de": "HSF", "en": "HSF"},
        2: {"de": "PHA", "en": "PHA"},
        3: {"de": "SHK", "en": "SHK"},
    },
    "KESSELTYP": {
        0: {"de": "Slave", "en": "Slave"},
        1: {"de": "Master", "en": "Master"},
        2: {"de": "Compact 25", "en": "Compact 25"},
        3: {"de": "Compact 35", "en": "Compact 35"},
        4: {"de": "Compact 50", "en": "Compact 50"},
        5: {"de": "Compact 65", "en": "Compact 65"},
        6: {"de": "Compact 80", "en": "Compact 80"},
        7: {"de": "K10", "en": "K10"},
        8: {"de": "K15", "en": "K15"},
        9: {"de": "K21", "en": "K21"},
        10: {"de": "K26", "en": "K26"},
        11: {"de": "K35", "en": "K35"},
        12: {"de": "K45", "en": "K45"},
        13: {"de": "K60", "en": "K60"},
        14: {"de": "F20", "en": "F20"},
        15: {"de": "F25", "en": "F25"},
        16: {"de": "F30", "en": "F30"},
        17: {"de": "F40", "en": "F40"},
        18: {"de": "F50", "en": "F50"},
        19: {"de": "Euro 30", "en": "Euro 30"},
        20: {"de": "Euro 40", "en": "Euro 40"},
        21: {"de": "Euro 50", "en": "Euro 50"},
        22: {"de": "H20", "en": "H20"},
        23: {"de": "H25", "en": "H25"},
        24: {"de": "H30", "en": "H30"},
        25: {"de": "FK Hybrid 20/15", "en": "FK Hybrid 20/15"},
        26: {"de": "FK Hybrid 30/15", "en": "FK Hybrid 30/15"},
        27: {"de": "FK Hybrid 30/26", "en": "FK Hybrid 30/26"},
        28: {"de": "FK Hybrid 40/26", "en": "FK Hybrid 40/26"},
        29: {"de": "FK Hybrid 50/26", "en": "FK Hybrid 50/26"},
        30: {"de": "K33", "en": "K33"},
        31: {"de": "Compact 40", "en": "Compact 40"},
        32: {"de": "Compact 95", "en": "Compact 95"},
        33: {"de": "Compact 30", "en": "Compact 30"},
        34: {"de": "K38", "en": "K38"},
        35: {"de": "K45 (2)", "en": "K45 (2)"},
        36: {"de": "K50", "en": "K50"},
        37: {"de": "K63", "en": "K63"},
    },
    "STROMNETZ": {
        0: {"de": "3x400V", "en": "3x400V"},
        1: {"de": "3x230V", "en": "3x230V"},
        2: {"de": "1x230V", "en": "1x230V"},
    },
    "BRENNSTOFF": {
        0: {"de": "Material 1", "en": "Fuel 1"},
        1: {"de": "Material 2", "en": "Fuel 2"},
        2: {"de": "Material 3", "en": "Fuel 3"},
        3: {"de": "Material 4", "en": "Fuel 4"},
    },
    "EINSTIEGSBILD": {
        0: {"de": "Heizkessel", "en": "Boiler"},
        1: {"de": "Puffer 1", "en": "Accumulator 1"},
        2: {"de": "Puffer 2", "en": "Accumulator 2"},
        3: {"de": "Ext. Wärmequelle", "en": "Ext. Heat Source"},
        4: {"de": "Heizkreis 1", "en": "Heating Circuit 1"},
        5: {"de": "Heizkreis 2", "en": "Heating Circuit 2"},
        6: {"de": "Heizkreis 3", "en": "Heating Circuit 3"},
        7: {"de": "Heizkreis 4", "en": "Heating Circuit 4"},
        8: {"de": "Heizkreis 5", "en": "Heating Circuit 5"},
        9: {"de": "Heizkreis 6", "en": "Heating Circuit 6"},
        10: {"de": "Netzpumpe 1", "en": "Network Pump 1"},
        11: {"de": "Netzpumpe 2", "en": "Network Pump 2"},
        12: {"de": "Netzpumpe 3", "en": "Network Pump 3"},
        13: {"de": "Brauchwasser 1", "en": "Domestic Hot Water 1"},
        14: {"de": "Brauchwasser 2", "en": "Domestic Hot Water 2"},
        15: {"de": "Solar", "en": "Solar"},
        16: {"de": "Austragung", "en": "Discharge System"},
    },
    "HOLZART": {
        0: {"de": "Hartholz", "en": "Hardwood"},
        1: {"de": "Mischholz", "en": "Mixed wood"},
        2: {"de": "Weichholz", "en": "Softwood"},
        3: {"de": "Sägereste", "en": "Sawing waste"},
        4: {"de": "Holzbriketts", "en": "Wood briquettes"},
    },
    "HOLZFEUCHTE": {
        0: {"de": "trockene Qualität", "en": "dry quality"},
        1: {"de": "mittlere Qualität", "en": "medium quality"},
        2: {"de": "feuchte Qualität", "en": "wet quality"},
    },
    "NACHLEGESCHRITT": {
        0: {"de": "1%-Schritte", "en": "1%-steps"},
        1: {"de": "5%-Schritte", "en": "5%-steps"},
        2: {"de": "10%-Schritte", "en": "10%-steps"},
    },
    "ANLAGE_BETRIEBSART": {
        0: {"de": "Normal", "en": "Normal"},
        1: {"de": "Urlaubsbetrieb", "en": "Holiday mode"},
        2: {"de": "Sommerbetrieb", "en": "Summer mode"},
        3: {"de": "Frostschutz", "en": "Frost protection"},
    },
    "BETRIEBSART_CURRENT": {
        0: {"de": "Aus", "en": "Off"},
        1: {"de": "Ein", "en": "On"},
        2: {"de": "Urlaubsbetrieb", "en": "Holiday mode"},
        3: {"de": "Sommerbetrieb", "en": "Summer mode"},
        4: {"de": "Frostschutz", "en": "Frost protection"},
    },
    "RAUMEINHEIT": {
        0: {"de": "Keine", "en": "None"},
        1: {"de": "Raumtemperaturfühler", "en": "Indoor thermostat unit"},
        2: {"de": "Raumbediengerät BUS", "en": "Room control unit BUS"},
        3: {"de": "Raumbediengerät LIGHT", "en": "Room control unit LIGHT"},
        4: {"de": "Raumbediengerät BUS NLM", "en": "Room control unit BUS(NLM)"},
        5: {"de": "Raumtemperaturfühler 2", "en": "Indoor thermostat unit 2"},
    },
    "QUELLE": {
        0: {"de": "Keine", "en": "None"},
        1: {"de": "Kessel", "en": "Boiler"},
        2: {"de": "Puffer 1", "en": "Accumulator 1"},
        3: {"de": "Puffer 2", "en": "Accumulator 2"},
        4: {"de": "Netzpumpe 1", "en": "Network pump 1"},
        5: {"de": "Netzpumpe 2", "en": "Network pump 2"},
        6: {"de": "Netzpumpe 3", "en": "Network pump 3"},
        7: {"de": "Verband", "en": "Master"},
        8: {"de": "Solar", "en": "Solar"},
    },
    "PUFFER_ART": {
        0: {"de": "Kein", "en": "None"},
        1: {"de": "Normal", "en": "Normal"},
        2: {"de": "Kombi", "en": "Combi"},
    },
    "HK_ESTRICHSCHRITT": {
        0: {"de": "Aus", "en": "Off"},
        1: {"de": "An - Anstieg", "en": "At - increase"},
        2: {"de": "An - Halten", "en": "At - hold"},
        3: {"de": "An - Abkühlen", "en": "At-cool down"},
    },
    "PUFFER_POS": {
        0: {"de": "Puffer oben", "en": "Accumulator top"},
        1: {"de": "Puffer unten", "en": "Accumulator bottom"},
        2: {"de": "Puffer mitte", "en": "Accumulator middle"},
        3: {"de": "Puffer mitte-oben", "en": "Accumulator middle upper"},
        4: {"de": "Puffer mitte-unten", "en": "Accumulator middle lower"},
        5: {"de": "Puffer Rücklauf", "en": "Accumulator Return"},
    },
    "NACHLEGEN_ANZEIGE": {
        0: {"de": "nicht möglich", "en": "not possible"},
        1: {"de": "erlaubt, aber Stillstandszeit", "en": "allowed, but idle time"},
        2: {"de": "möglich und sinnvoll", "en": "possible and useful"},
        3: {"de": "notwendig, oder es wird kalt", "en": "necessary, or it gets cold"},
    },
    "KESSELAUSBRENNBEZUG": {
        0: {"de": "Standard", "en": "Standard"},
        1: {"de": "Restsauerstoff", "en": "Residual Oxygen"},
        2: {"de": "Abgastemperatur", "en": "Flue Gas Temperature"},
    },
}

HDG_STRING_ENUM_MAPPINGS: Final[dict[str, dict[str, StringEnumOption]]] = {
    "KESSEL_BETRIEBSART_STRINGS": {
        "Normal": {"de": "Normal", "en": "Normal"},
        "Day mode": {"de": "Tagbetrieb", "en": "Day mode"},
        "Night mode": {"de": "Nachtbetrieb", "en": "Night mode"},
        "Party mode": {"de": "Partybetrieb", "en": "Party mode"},
        "Holiday mode": {"de": "Urlaubsbetrieb", "en": "Holiday mode"},
        "Summer mode": {"de": "Sommerbetrieb", "en": "Summer mode"},
    },
    "HK_BETRIEBSART_STRINGS": {
        "NORMAL": {"de": "Normal", "en": "Normal"},
        "TAG": {"de": "Tagbetrieb", "en": "Day mode"},
        "NACHT": {"de": "Nachtbetrieb", "en": "Night mode"},
        "PARTY": {"de": "Partybetrieb", "en": "Party mode"},
        "SOMMER": {"de": "Sommerbetrieb", "en": "Summer mode"},
    },
}
